#
server.port: 8888

logging:
  level:
    com.siyueren.*: debug

spring.redis:
  database: 0
  host: 127.1
  port: 6380
  password: mima
  jedis.pool.max-active: 1000
  jedis.pool.max-wait: -1
  jedis.pool.max-idle: 300
  jedis.pool.min-idle: 0
  timeout: 10000